---
services:

  mosquitto:
    image: eclipse-mosquitto:1.6.13
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ../../ccloud/fm-mqtt-sink/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../../ccloud/fm-mqtt-sink/password:/etc/mosquitto/passwd

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - mosquitto
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-mqtt-sink/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN